Avoid random failures caused by unexpected content change
org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up
Command duration or timeout: 2.19 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'jenkins', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.9.4-1-mansion', java.version: '1.8.0_20-ea'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=22.0, platform=LINUX, browserConnectionEnabled=true, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: aae24c41-bb95-415c-99b1-9b8e7be24d0f
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
        at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:152)
        at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:331)
        at com.sun.proxy.$Proxy34.getText(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.getText(EventFiringWebDriver.java:381)
        at org.jenkinsci.test.acceptance.Matchers$1.pageText(Matchers.java:47)
        at org.jenkinsci.test.acceptance.Matchers$1.matchesSafely(Matchers.java:34)
        at org.jenkinsci.test.acceptance.Matchers$1.matchesSafely(Matchers.java:28)
        at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:64)
        at org.hamcrest.core.IsNot.matches(IsNot.java:24)
        at org.jenkinsci.test.acceptance.po.CapybaraPortingLayerImpl$2.call(CapybaraPortingLayerImpl.java:146)
        at org.jenkinsci.test.acceptance.po.CapybaraPortingLayerImpl$2.call(CapybaraPortingLayerImpl.java:144)
        at org.jenkinsci.test.acceptance.po.CapybaraPortingLayerImpl.waitForCond(CapybaraPortingLayerImpl.java:128)
        at org.jenkinsci.test.acceptance.po.CapybaraPortingLayerImpl.waitFor(CapybaraPortingLayerImpl.java:144)
        at org.jenkinsci.test.acceptance.po.Jenkins.restart(Jenkins.java:119)
        at org.jenkinsci.test.acceptance.junit.WithPlugins$RuleImpl$1.evaluate(WithPlugins.java:91)
        at org.jenkinsci.test.acceptance.junit.JenkinsAcceptanceTestRule$1.evaluate(JenkinsAcceptanceTestRule.java:59)
        at org.jenkinsci.test.acceptance.junit.FilterRule$1.evaluate(FilterRule.java:61)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'
System info: host: 'jenkins', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.9.4-1-mansion', java.version: '1.8.0_20-ea'
Driver info: driver.version: unknown
        at <anonymous class>.fxdriver.cache.getElementAt(resource://fxdriver/modules/web-element-cache.js:8329)
        at <anonymous class>.Utils.getElementAt(file:///tmp/anonymous3880783028938283646webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:7922)
        at <anonymous class>.WebElement.getElementText(file:///tmp/anonymous3880783028938283646webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11065)
        at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///tmp/anonymous3880783028938283646webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11635)
        at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///tmp/anonymous3880783028938283646webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:548)