Don't display an ugly stacktrace if the JENKINS_HOME doesn't exist when cleaning up
java.lang.RuntimeException: java.io.FileNotFoundException: File does not exist: [redacted]
  at org.jenkinsci.test.acceptance.controller.LocalController.tearDown(LocalController.java:295)
  at org.jenkinsci.test.acceptance.controller.JenkinsController.close(JenkinsController.java:138)
  at org.jenkinsci.test.acceptance.guice.TestCleaner.performCleanUp(TestCleaner.java:23)
  at org.jenkinsci.test.acceptance.guice.World.endTestScope(World.java:66)
  at org.jenkinsci.test.acceptance.junit.JenkinsAcceptanceTestRule$1.evaluate(JenkinsAcceptanceTestRule.java:64)
  ... 30 more
Caused by: java.io.FileNotFoundException: File does not exist: [redacted]
  at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2275)
  at org.jenkinsci.test.acceptance.controller.LocalController.tearDown(LocalController.java:286)
  ... 35 more