Capybara 2.0 compatibility not verified yet.
The error I get is this:

undefined method `body' for class `Sauce::Capybara::Driver' (NameError)
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/sauce-2.1.0/lib/sauce/capybara.rb:57:in `<class:Driver>'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/sauce-2.1.0/lib/sauce/capybara.rb:23:in `<module:Capybara>'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/sauce-2.1.0/lib/sauce/capybara.rb:11:in `<module:Sauce>'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/sauce-2.1.0/lib/sauce/capybara.rb:10:in `<top (required)>'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/sauce-cucumber-2.1.1/lib/sauce/cucumber.rb:4:in `require'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/sauce-cucumber-2.1.1/lib/sauce/cucumber.rb:4:in `<top (required)>'
/home/jenkins/slave/workspace/selenium-tests/features/support/env.rb:7:in `require'
/home/jenkins/slave/workspace/selenium-tests/features/support/env.rb:7:in `<top (required)>'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/cucumber-1.2.1/lib/cucumber/rb_support/rb_language.rb:129:in `load'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/cucumber-1.2.1/lib/cucumber/rb_support/rb_language.rb:129:in `load_code_file'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/cucumber-1.2.1/lib/cucumber/runtime/support_code.rb:171:in `load_file'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/cucumber-1.2.1/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/cucumber-1.2.1/lib/cucumber/runtime/support_code.rb:82:in `each'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/cucumber-1.2.1/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/cucumber-1.2.1/lib/cucumber/runtime.rb:175:in `load_step_definitions'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/cucumber-1.2.1/lib/cucumber/runtime.rb:40:in `run!'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/cucumber-1.2.1/lib/cucumber/cli/main.rb:43:in `execute!'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/cucumber-1.2.1/lib/cucumber/cli/main.rb:20:in `execute'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/gems/cucumber-1.2.1/bin/cucumber:14:in `<top (required)>'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/bin/cucumber:19:in `load'
/home/jenkins/.rvm/gems/ruby-1.9.3-p0@selenium-tests/bin/cucumber:19:in `<main>'
rake aborted!