Add extra debuging and fix controller logs
The controller logs just use master0000 as the logId was using the port
and since we use dynamic port the value is non stable (changes during he
test) and also collides (every controller will start as master0000)

Also adds diadnostic logging to HARRecprder as I have been seeing tests
where firefox can not connect to Jenkins as the browser is not running
and test failures where the HAR can not be gathered as the proxy has
already been stopped.

```
java.lang.IllegalStateException: Proxy server is already stopped. Cannot re-stop.
	at com.browserup.bup.BrowserUpProxyServer.stop(BrowserUpProxyServer.java:514)
	at com.browserup.bup.BrowserUpProxyServer.stop(BrowserUpProxyServer.java:493)
	at org.jenkinsci.test.acceptance.recorder.HarRecorder.recordHar(HarRecorder.java:120)
	at org.jenkinsci.test.acceptance.recorder.HarRecorder.failed(HarRecorder.java:114)
	at org.junit.rules.TestWatcher.failedQuietly(TestWatcher.java:90
```

```
org.openqa.selenium.WebDriverException:
Reached error page: about:neterror?e=proxyConnectFailure&u=http%3A//mvn%3A42593/pluginManager/available&c=UTF-8&d=Firefox%20is%20configured%20to%20use%20a%20proxy%20server%20that%20is%20refusing%20connections.
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-1030-gcp', java.version: '11.0.18'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [9241c692-6c94-4037-b34b-273cf4e18279, get {url=http://mvn:42593/pluginManager/available}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 106.0.4, moz:accessibilityChecks: false, moz:buildID: 20221102214123, moz:debuggerAddress: 127.0.0.1:20092, moz:firefoxOptions: {prefs: {dom.disable_beforeunload: false, dom.max_chrome_script_run_time: 600000, dom.max_script_run_time: 600000, intl.accept_languages: en}}, moz:geckodriverVersion: 0.32.0, moz:headless: false, moz:platformVersion: 5.15.0-1030-gcp, moz:processID: 1075, moz:profile: /tmp/rust_mozprofilerHfdHB, moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(manual, http=mvn:4367..., se:bidi: ws://172.18.0.2:4444/sessio..., se:cdp: ws://172.18.0.2:4444/sessio..., se:cdpVersion: 85.0, se:noVncPort: 7900, se:vnc: ws://172.18.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.18.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 9241c692-6c94-4037-b34b-273cf4e18279
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:297)
```