more envs needed for port control of selenium 4
ammends #1100 even with the fix of the port flag selenium would not
start due to

11:43:39.232 INFO [LocalDistributor.newSession] - Session request received by the Distributor:
 [Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {prefs: {dom.disable_beforeunload: false, dom.max_chrome_script_run_time: 600000, dom.max_script_run_time: 600000, intl.accept_languages: en}}, proxy: {httpProxy: localhost:33435, proxyType: manual, sslProxy: localhost:33435}}, Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {prefs: {dom.disable_beforeunload: false, dom.max_chrome_script_run_time: 600000, dom.max_script_run_time: 600000, intl.accept_languages: en}}, proxy: {httpProxy: localhost:33435, proxyType: MANUAL, sslProxy: localhost:33435}}]
1680781419259   geckodriver     INFO    Listening on 127.0.0.1:21862
1680781419500   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "--remote-debugging-port" "6734" "--remote-allow-hosts" "localhost" "--remote-allow-origins" "http://127.0.0.1:6734/,http://localhost:6734/,http://[::1]:6734/" "-no-remote" "-profile" "/tmp/rust_mozprofilebyn9Y6"
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :17
11:43:39.626 WARN [DriverServiceSessionFactory.apply] - Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 1
Host info: host: 'debian', ip: '127.0.1.1'
Build info: version: '4.6.0', revision: '79f1c02ae20'

more variables need to be set to configure the display xvfb and vnc.
reverse engineered from the docker file and tested in a linux VM with

export JAVA_OPTS=-Djava.awt.headless=true
export JENKINS_JAVA_OPTS="-Xmx1280m -Djava.awt.headless=true"
export JENKINS_WAR=target/jenkins-war.war
export BROWSER=firefox-container
mvn test -Dtest=CreateItemTest